# Generated by Django 2.1.3 on 2018-11-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_nov6', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=254),
        ),
    ]
